# Generated by Django 3.2.18 on 2023-04-05 12:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('adminapp', '0004_remove_user_zendeskorganization'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, unique=True)),
                ('productName', models.CharField(blank=True, max_length=200, null=True)),
                ('stripePlanKey', models.CharField(blank=True, max_length=200, null=True)),
                ('noOfRewordsPerDay', models.IntegerField(default=0)),
                ('suitableForTeam', models.IntegerField(default=0)),
                ('price', models.IntegerField(default=0)),
                ('discount', models.IntegerField(blank=True, null=True)),
                ('description', models.CharField(blank=True, max_length=5000, null=True)),
                ('interval', models.CharField(blank=True, max_length=30, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdTime', models.DateTimeField(auto_now_add=True)),
                ('accounOwner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminapp.user')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='billing.plan')),
            ],
        ),
    ]
