# Generated by Django 3.2.18 on 2023-04-07 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0003_auto_20230406_1531'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='subscriptionStartsAt',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
