# Generated by Django 3.2.18 on 2023-05-11 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0004_subscription_subscriptionstartsat'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='renewPlanDate',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
