# Generated by Django 4.1.7 on 2023-03-21 06:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('adminapp', '0002_user_issuspended_user_zendeskcreatedusertime_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('roleId', models.BigAutoField(primary_key=True, serialize=False)),
                ('agentRole', models.CharField(max_length=500)),
                ('createdBy', models.IntegerField(blank=True, null=True)),
                ('createdOnUtc', models.DateTimeField(auto_now_add=True)),
                ('modifiedBy', models.IntegerField(blank=True, null=True)),
                ('modifiedOnUtc', models.DateTimeField(auto_now=True)),
                ('isDeleted', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Sentiment',
            fields=[
                ('sentimentId', models.BigAutoField(primary_key=True, serialize=False)),
                ('customerSentiment', models.CharField(max_length=500)),
                ('createdBy', models.IntegerField(blank=True, null=True)),
                ('createdOnUtc', models.DateTimeField(auto_now_add=True)),
                ('modifiedBy', models.IntegerField(blank=True, null=True)),
                ('modifiedOnUtc', models.DateTimeField(auto_now=True)),
                ('isDeleted', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Tone',
            fields=[
                ('toneId', models.BigAutoField(primary_key=True, serialize=False)),
                ('replyTone', models.CharField(max_length=500)),
                ('createdBy', models.IntegerField(blank=True, null=True)),
                ('createdOnUtc', models.DateTimeField(auto_now_add=True)),
                ('modifiedBy', models.IntegerField(blank=True, null=True)),
                ('modifiedOnUtc', models.DateTimeField(auto_now=True)),
                ('isDeleted', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='RoleSentimentToneMapping',
            fields=[
                ('rstId', models.BigAutoField(primary_key=True, serialize=False)),
                ('createdBy', models.IntegerField(blank=True, null=True)),
                ('createdOnUtc', models.DateTimeField(auto_now_add=True)),
                ('modifiedBy', models.IntegerField(blank=True, null=True)),
                ('modifiedOnUtc', models.DateTimeField(auto_now=True)),
                ('isDeleted', models.BooleanField(default=False)),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='master.role')),
                ('sentiment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='master.sentiment')),
                ('tone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='master.tone')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminapp.user')),
            ],
        ),
    ]
