# Generated by Django 4.1.7 on 2023-03-30 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0002_remove_rolesentimenttonemapping_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='role',
            name='agentRole',
        ),
        migrations.RemoveField(
            model_name='sentiment',
            name='customerSentiment',
        ),
        migrations.RemoveField(
            model_name='tone',
            name='replyTone',
        ),
        migrations.AddField(
            model_name='role',
            name='agentRoleAPI',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='role',
            name='agentRoleUI',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='sentiment',
            name='customerSentimentAPI',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='sentiment',
            name='customerSentimentUI',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='tone',
            name='replyToneAPI',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='tone',
            name='replyToneUI',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
