# Generated by Django 3.2.18 on 2023-03-31 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0003_remove_role_agentrole_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='accountOwnerID',
            field=models.CharField(default=1, max_length=50),
        ),
        migrations.AddField(
            model_name='sentiment',
            name='accountOwnerID',
            field=models.CharField(default=1, max_length=50),
        ),
        migrations.AddField(
            model_name='tone',
            name='accountOwnerID',
            field=models.CharField(default=1, max_length=50),
        ),
    ]
