# Generated by Django 3.2.18 on 2023-04-04 13:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0004_remove_user_zendeskorganization'),
        ('master', '0004_auto_20230331_1525'),
    ]

    operations = [
        migrations.AddField(
            model_name='rolesentimenttonemapping',
            name='user_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='adminapp.user'),
        ),
    ]
