# Generated by Django 3.2.18 on 2023-04-17 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0005_rolesentimenttonemapping_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rolesentimenttonemapping',
            name='zendeskOrganizationId',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
