# Generated by Django 3.2.18 on 2023-08-07 07:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0007_language_yesnoinstructtone'),
    ]

    operations = [
        migrations.AddField(
            model_name='rolesentimenttonemapping',
            name='language',
            field=models.ForeignKey(null= True, blank=True, on_delete=django.db.models.deletion.CASCADE, to='master.language'),
        ),
        migrations.AddField(
            model_name='rolesentimenttonemapping',
            name='yni_tone',
            field=models.ForeignKey(null= True, blank=True, on_delete=django.db.models.deletion.CASCADE, to='master.yesnoinstructtone'),
        ),
    ]
