# Generated by Django 3.2.18 on 2023-08-09 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0008_auto_20230807_1323'),
    ]

    operations = [
        migrations.AddField(
            model_name='rolesentimenttonemapping',
            name='isLanguageIgnoredForInstruct',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='rolesentimenttonemapping',
            name='isYniToneIgnoredForInstruct',
            field=models.BooleanField(default=False),
        ),
    ]
