# Generated by Django 3.2.18 on 2023-08-09 13:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0009_auto_20230809_1234'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rolesentimenttonemapping',
            name='language',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='master.language'),
        ),
        migrations.AlterField(
            model_name='rolesentimenttonemapping',
            name='yni_tone',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='master.yesnoinstructtone'),
        ),
    ]
