# Generated by Django 4.1.7 on 2023-03-17 11:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('userId', models.BigAutoField(primary_key=True, serialize=False)),
                ('authOUid', models.CharField(blank=True, max_length=20, null=True)),
                ('name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=50, unique=True)),
                ('role', models.CharField(max_length=50)),
                ('createdBy', models.IntegerField(blank=True, null=True)),
                ('createdOnUtc', models.DateTimeField(auto_now_add=True)),
                ('modifiedBy', models.IntegerField(blank=True, null=True)),
                ('modifiedOnUtc', models.DateTimeField(auto_now=True)),
                ('isDeleted', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='HitCount',
            fields=[
                ('hitCountId', models.BigAutoField(primary_key=True, serialize=False)),
                ('hitTime', models.DateTimeField(auto_now_add=True)),
                ('promptText', models.CharField(blank=True, max_length=10000, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminapp.user')),
            ],
        ),
    ]
