# Generated by Django 4.1.7 on 2023-03-21 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0002_user_issuspended_user_zendeskcreatedusertime_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='zendeskOrganization',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='zendeskOrganizationId',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
