# Generated by Django 4.1.7 on 2023-03-21 08:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0003_user_zendeskorganization_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='zendeskOrganization',
        ),
    ]
