# Generated by Django 3.2.18 on 2023-04-10 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0004_remove_user_zendeskorganization'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='zendeskOrganizationName',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
