# Generated by Django 3.2.18 on 2023-04-11 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0005_user_zendeskorganizationname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='zendeskOrganizationId',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
    ]
